stop

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,66 +29,66 @@ jobs:
       targets: '["pacsync"]'
       platforms: '["linux"]'
 
-  aur_deploy:
-    name: AUR
-    runs-on: ubuntu-latest
-    needs: cd
-    if: needs.cd.outputs.releaseCreated == 'true'
-    container: archlinux:base-devel
-    steps:
-      - name: Install pacman dependencies
-        run: sudo pacman -Sy --noconfirm git openssh go-yq pacman-contrib dart namcap
-      - name: Create build user
-        run: |
-          set -exo pipefail
-          useradd -m -G wheel -s /bin/bash -d /build build
-          echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
-      - name: Checkout source repository
-        uses: actions/checkout@v2
-        with:
-          path: src
-      - name: Prepare SSH for AUR repo checkout
-        run: |
-          set -exo pipefail
-          mkdir -p /etc/ssh
+  # aur_deploy:
+  #   name: AUR
+  #   runs-on: ubuntu-latest
+  #   needs: cd
+  #   if: needs.cd.outputs.releaseCreated == 'true'
+  #   container: archlinux:base-devel
+  #   steps:
+  #     - name: Install pacman dependencies
+  #       run: sudo pacman -Sy --noconfirm git openssh go-yq pacman-contrib dart namcap
+  #     - name: Create build user
+  #       run: |
+  #         set -exo pipefail
+  #         useradd -m -G wheel -s /bin/bash -d /build build
+  #         echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers
+  #     - name: Checkout source repository
+  #       uses: actions/checkout@v2
+  #       with:
+  #         path: src
+  #     - name: Prepare SSH for AUR repo checkout
+  #       run: |
+  #         set -exo pipefail
+  #         mkdir -p /etc/ssh
 
-          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" >> "$RUNNER_TEMP/ssh-key"
-          chmod 600 "$RUNNER_TEMP/ssh-key"
+  #         echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" >> "$RUNNER_TEMP/ssh-key"
+  #         chmod 600 "$RUNNER_TEMP/ssh-key"
 
-          echo "Host aur.archlinux.org" > /etc/ssh/ssh_config
-          echo "  IdentityFile $RUNNER_TEMP/ssh-key" >> /etc/ssh/ssh_config
-          echo "  User aur" >> /etc/ssh/ssh_config
+  #         echo "Host aur.archlinux.org" > /etc/ssh/ssh_config
+  #         echo "  IdentityFile $RUNNER_TEMP/ssh-key" >> /etc/ssh/ssh_config
+  #         echo "  User aur" >> /etc/ssh/ssh_config
 
-          echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN" >> /etc/ssh/ssh_known_hosts
-          echo "aur.archlinux.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLMiLrP8pVi5BFX2i3vepSUnpedeiewE5XptnUnau+ZoeUOPkpoCgZZuYfpaIQfhhJJI5qgnjJmr4hyJbe/zxow=" >> /etc/ssh/ssh_known_hosts
-          echo "aur.archlinux.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKF9vAFWdgm9Bi8uc+tYRBmXASBb5cB5iZsB7LOWWFeBrLp3r14w0/9S2vozjgqY5sJLDPONWoTTaVTbhe3vwO8CBKZTEt1AcWxuXNlRnk9FliR1/eNB9uz/7y1R0+c1Md+P98AJJSJWKN12nqIDIhjl2S1vOUvm7FNY43fU2knIhEbHybhwWeg+0wxpKwcAd/JeL5i92Uv03MYftOToUijd1pqyVFdJvQFhqD4v3M157jxS5FTOBrccAEjT+zYmFyD8WvKUa9vUclRddNllmBJdy4NyLB8SvVZULUPrP3QOlmzemeKracTlVOUG1wsDbxknF1BwSCU7CmU6UFP90kpWIyz66bP0bl67QAvlIc52Yix7pKJPbw85+zykvnfl2mdROsaT8p8R9nwCdFsBc9IiD0NhPEHcyHRwB8fokXTajk2QnGhL+zP5KnkmXnyQYOCUYo3EKMXIlVOVbPDgRYYT/XqvBuzq5S9rrU70KoI/S5lDnFfx/+lPLdtcnnEPk=" >> /etc/ssh/ssh_known_hosts
+  #         echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN" >> /etc/ssh/ssh_known_hosts
+  #         echo "aur.archlinux.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLMiLrP8pVi5BFX2i3vepSUnpedeiewE5XptnUnau+ZoeUOPkpoCgZZuYfpaIQfhhJJI5qgnjJmr4hyJbe/zxow=" >> /etc/ssh/ssh_known_hosts
+  #         echo "aur.archlinux.org ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKF9vAFWdgm9Bi8uc+tYRBmXASBb5cB5iZsB7LOWWFeBrLp3r14w0/9S2vozjgqY5sJLDPONWoTTaVTbhe3vwO8CBKZTEt1AcWxuXNlRnk9FliR1/eNB9uz/7y1R0+c1Md+P98AJJSJWKN12nqIDIhjl2S1vOUvm7FNY43fU2knIhEbHybhwWeg+0wxpKwcAd/JeL5i92Uv03MYftOToUijd1pqyVFdJvQFhqD4v3M157jxS5FTOBrccAEjT+zYmFyD8WvKUa9vUclRddNllmBJdy4NyLB8SvVZULUPrP3QOlmzemeKracTlVOUG1wsDbxknF1BwSCU7CmU6UFP90kpWIyz66bP0bl67QAvlIc52Yix7pKJPbw85+zykvnfl2mdROsaT8p8R9nwCdFsBc9IiD0NhPEHcyHRwB8fokXTajk2QnGhL+zP5KnkmXnyQYOCUYo3EKMXIlVOVbPDgRYYT/XqvBuzq5S9rrU70KoI/S5lDnFfx/+lPLdtcnnEPk=" >> /etc/ssh/ssh_known_hosts
 
-          git config --global user.name "$GITHUB_ACTOR"
-          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
-      - name: Clone AUR repository
-        run: git clone "ssh://aur@aur.archlinux.org/$(yq ".name" src/pubspec.yaml).git" ./aur
-      - run: dart pub get
-        working-directory: src
-      - run: dart run build_runner build
-        working-directory: src
-      - run: dart run tool/makepkg/generate_pkgbuild.dart ../aur
-        working-directory: src
-      - run: chown -R build:build aur
-      - run: su build -c updpkgsums
-        working-directory: aur
-      - run: su build -c "namcap -i PKGBUILD"
-        working-directory: aur
-      - run: su build -c "makepkg -sfC --check --noconfirm"
-        working-directory: aur
-      - run: su build -c "makepkg --printsrcinfo > .SRCINFO"
-        working-directory: aur
-      - run: chown -R root:root aur
-      - run: git add PKGBUILD CHANGELOG.md .SRCINFO
-        working-directory: aur
-      - run: git commit -m "Update $(yq ".name" ../src/pubspec.yaml) to version $(yq ".version" ../src/pubspec.yaml)"
-        working-directory: aur
-      - run: git push
-        working-directory: aur
-      - name: Clean up ssh key
-        if: always()
-        run: shred -fzvu "$RUNNER_TEMP/ssh-key"
+  #         git config --global user.name "$GITHUB_ACTOR"
+  #         git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
+  #     - name: Clone AUR repository
+  #       run: git clone "ssh://aur@aur.archlinux.org/$(yq ".name" src/pubspec.yaml).git" ./aur
+  #     - run: dart pub get
+  #       working-directory: src
+  #     - run: dart run build_runner build
+  #       working-directory: src
+  #     - run: dart run tool/makepkg/generate_pkgbuild.dart ../aur
+  #       working-directory: src
+  #     - run: chown -R build:build aur
+  #     - run: su build -c updpkgsums
+  #       working-directory: aur
+  #     - run: su build -c "namcap -i PKGBUILD"
+  #       working-directory: aur
+  #     - run: su build -c "makepkg -sfC --check --noconfirm"
+  #       working-directory: aur
+  #     - run: su build -c "makepkg --printsrcinfo > .SRCINFO"
+  #       working-directory: aur
+  #     - run: chown -R root:root aur
+  #     - run: git add PKGBUILD CHANGELOG.md .SRCINFO
+  #       working-directory: aur
+  #     - run: git commit -m "Update $(yq ".name" ../src/pubspec.yaml) to version $(yq ".version" ../src/pubspec.yaml)"
+  #       working-directory: aur
+  #     - run: git push
+  #       working-directory: aur
+  #     - name: Clean up ssh key
+  #       if: always()
+  #       run: shred -fzvu "$RUNNER_TEMP/ssh-key"
